### PR TITLE
Added query for device info

### PR DESCRIPTION
**Pull request by ncmiller**
Added devinfo() to Roku class in core.py, which issues a GET on 'query/device-info' and parses out a few interesting fields. 

This allows me to resolve ncmiller/roku-cli/issues/1.

### CODE REVIEW

**Comment by jcarbaugh** [comment]
Thanks much for the PR! Would you be open to changing the name of the property to either `device_info` or just `info`? I'd like it to be explicit since `devinfo` might be inferred to mean development info. Just plain `info` might be okay too since a Roku object represents a single device.

**Comment by ncmiller** [comment]
Good suggestion. I'm a little conflicted with `info`, because that's the name of a command. In fact, that was the original name I used, but `testCommands` failed because of the name clash. So I lean slightly towards `device_info`. Is that okay? If so, I can update the PR.

**Comment by jcarbaugh** [comment]
@ncmiller oh, good call with the info conflict. Yeah, let's got with `device_info` then. Very much appreciated!

**Comment by ncmiller** [comment]
Let me know if there's anything else you'd like to see before merging. Thanks!

**Comment by jcarbaugh** [comment]
Thanks for making the change!

**Pull request merged**
