### PR TITLE
Include all successful HTTP status codes

### PR DESCRIPTION
**Pull request by springstan**
Fixes home-assistant/home-assistant#29591

Description:
-  include all successful http status codes instead of only two of them
- more details: https://github.com/home-assistant/home-assistant/issues/29591#issuecomment-562884172

### CODE REVIEW

**Comment by jcarbaugh** [comment]
Thanks! I'll get a new release ready tonight or tomorrow.

**Comment by springstan** [comment]
Of course! That is great to hear, thanks for reviewing this PR so quickly :)

**Comment by jcarbaugh** [comment]
@springstan Just pushed v4 to PyPI. Really glad to get that fixed for HA!

**Comment by springstan** [comment]
@jcarbaugh really appreciate that you are informing me about this, thanks!
I am sicked as well! If you do not mind I will open a new PR to bump up the version in HA.

**Comment by jcarbaugh** [comment]
@springstan it would be great if you could open the PR against HA! Much appreciated.

**Pull request merged**
